# -*- coding: utf-8 -*-
"""sensor_sense.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nuS1ESVfnH3osH5KQcStd-nBFz0F8j1M
"""

import pandas as pd
import numpy as np

truth = pd.read_csv('/content/groundTruth.csv')
dataset = pd.read_csv('/content/dataset.csv')

dataset.head()

truth.head()

d = {'curva_direita_agressiva': 0,
 'curva_esquerda_agressiva': 1,
 'evento_nao_agressivo': 2,
 'troca_faixa_direita_agressiva': 3}

for i in range(len(truth)):
    truth['evento'][i] = d[truth['evento'][i]]

truth.head()

print(truth.columns)

def create_dataset():
    train_data = []
    labels = []
    j = 0
    for i in range(len(dataset)):
        while(dataset['uptimeNanos'][i] >= truth[' inicio'][j] and dataset['uptimeNanos'][i] < truth['fim'][j]):
            train_data.append([dataset['x_acct'][i], dataset['y_acct'][i], dataset['z_acct'][i], 
                               dataset['x_giro'][i], dataset['y_giro'][i], dataset['z_giro'][i],
                               dataset['x_accl'][i], dataset['y_accl'][i], dataset['z_accl'][i]])
        else:
            j += 1    
    return(np.array(train_data))

train_data = create_dataset()



